### ISSUE TITLE
Review Dependabot alerts

### ISSUE THREAD

**Issue by lladdy** [aiarena/aiarena-docker-base#173]
Tensorflow and pytorch appear to be minor version updates.

**Comment by lladdy** [comment]
https://github.com/aiarena/aiarena-docker-base/security/dependabot

**Comment by alkurbatov** [comment]
The following list was created from the list of currently open security issues (see the Security tab). This list might be not complete as there are 25 opened PRs, some of which not mentioned in the list.

## Image dependencies
### Major updates
certifi, 2022.5.18.1 -> 2023.7.22
requests, 2.27.1 -> 2.31.0
scipy, 1.8.1 -> 1.10.0
sqlalchemy, 1.4.36 -> 2.0.22
tensorflow, 2.9.0 -> 2.11.1
urllib3, 1.26.9 -> 1.26.18


### Minor updates
aiohttp, 3.8.1 -> 3.8.6
future,  0.18.2 -> 0.18.3
protobuf, 3.20.1 -> 3.20.2
torch, 1.11.0 -> 1.13.1

## Dependencies of our packages
(could be resolved by changing poetry.lock and trigger updates in our dependencies)

### Major updates
Pillow, 9.1.1 -> 10.0.1
Werkzeug , 2.1.2 -> 2.2.3
grpcio, 1.46.3 -> 1.53.0
joblib, 1.1.0 -> 1.2.0

### Minor updates
oauthlib, 3.2.0 -> 3.2.2

**Comment by alkurbatov** [comment]
Most of the updates change major version and might affect bots.

**Comment by lladdy** [comment]
Thanks @alkurbatov 
Closing this as done.

I've created a new task here for updating the deps at the end of the season:
https://github.com/aiarena/aiarena-docker-base/issues/175
