### ISSUE TITLE
Install Python 3.11

### ISSUE THREAD

**Issue by raspersc2** [aiarena/aiarena-docker-base#88]
Originally suggested by BuRny on discord

https://docs.python.org/3.11/whatsnew/3.11.html#faster-cpython

> CPython 3.11 is on average [25% faster](https://github.com/faster-cpython/ideas/blob/main/main-vs-310.rst) than CPython 3.10 when measured with the [pyperformance](https://github.com/python/pyperformance) benchmark suite, and compiled with GCC on Ubuntu Linux. Depending on your workload, the speedup could be up to 10-60% faster.

The community would need some notice since compiled code relies on a specific python version.

**Comment by BurnySc2** [comment]
Python 3.11 is not out yet :)
It will be out some time in october, and then it will take a few months before all major packages support Python 3.11, so I suggest revisiting this early in 2023
